### ISSUE TITLE
Potential copyright infringement

### ISSUE THREAD

**Issue by RealJammy** [AppliedCyberCTF/National-Cyber-Scholarship-2021#2]
This repo was based off https://github.com/Alic3C/Cyber-FastTrack-Spring-2021, which **is not** in the public domain and there was no permission to use this layout from the creators of this repo.

**Comment by 404dcd** [comment]
+1, you have no rights to use this.

**Comment by chop0** [comment]
That's rather rude.  When our lord Lyne first created the earth, he also created the 7 deadly sins;  one of which being "Thou Shalt Not Steal From Alice" (preceded by "Thou Shalt Not Collect My Debt").

**Comment by 404dcd** [comment]
Applied Cybersecurity Society

For the attention of: Vishnuu Gopi
09 April 2021

Dear Vishnuu Gopi,

**Re: Alice3C/Cyber-FastTrack-Spring-2021 (the Work) by Alice C (the Author)**

We are the owners of all copyright subsisting in the Work, which is an original literary work created on 06 April 2021 by the Author and which has been protected as a copyright work under the provisions of the Copyright Designs and Patents Act 1988 since that date.

We now understand that your work entitled **README.md** (**the Infringing Work**) is substantially similar to the Work. 

As our consent to use the Work in this manner was neither sought nor granted we must inform you that you are in breach of copyright and we hereby request that you immediately:

1. cease all infringing conduct and cease publishing and /or distributing the Infringing Work;

2. deliver to us any and all copies of the Infringing Work;

3. deliver to us a written undertaking that you will immediately desist from infringing the Work and will seek our express written consent for any future use of the Work;

We expect your acknowledgement of this letter and your response to our requests by **10 April 2021**. Failure to respond by this date will result in us seeking further legal remedies.

Yours sincerely, 
CDSkids

**Comment by vgopi1** [comment]
Letter acknowledged. Working on resolving this now.

**Comment by 404dcd** [comment]
@vgopi1 That copyright letter was a joke, but we would like our template removed. Thanks for your cooperation, and we're happy to collaborate in the future :-)
